title: Penguin Classification Dashboard
description: Displaying the latest classified penguin data
baseurl: ""
url: ""

theme: minima

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/