title: Penguin Classification Project
description: >-
  A machine learning project that classifies penguin species based on their physical measurements,
  featuring daily updates and historical data visualization.
baseurl: "/Penguins_Clasification_Adelie"
url: ""

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude development-related files
exclude:
  - .git/
  - .github/
  - __pycache__/
  - logs/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/